version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: portfolio-db
    restart: always
    environment:
      MYSQL_DATABASE: dockerdeploy
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3310:3306"   # host 3307 mapped to container 3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - portfolio-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: portfolio-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/dockerdeploy
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"  # map container 8080 to host 8081 to avoid conflict
    networks:
      - portfolio-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: portfolio-frontend
    restart: always
    ports:
      - "8087:80"   # host 8082 map to nginx 80
    depends_on:
      - backend
    networks:
      - portfolio-net

volumes:
  db_data:

networks:
  portfolio-net:
    driver: bridge